var _menu = [{
    "menuName": "主页",
    "subMenus": [{
        "subMenuName": "主页-子菜单1",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单1-百度",
            "icon": "icon-nav",
            "url":"http://baidu.com"
        }, {
            "itemName": "子菜单1-搜狐",
            "icon": "icon-nav",
            "url": "http://sohu.com"
        }, {
            "itemName": "子菜单1-网易",
            "icon": "icon-nav",
            "url":"http://163.com"
        }, {
            "itemName": "子菜单1-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "主页-子菜单2",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单2-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "主页-子菜单3",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单3-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }]
}, {
    "menuName": "管理",
    "subMenus": [{
        "subMenuName": "管理-子菜单1",
        "icon": "icon-sys",
        "items": [{
            "itemName": "用户账号编辑",
            "icon": "icon-nav",
            "url": "/UserEdit.aspx"
        }, {
            "itemName": "职员信息编辑",
            "icon": "icon-nav",
            "url": "/EmployeeEdit.aspx"
        }, {
            "itemName": "子菜单1-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "管理-子菜单2",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单2-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "管理-子菜单3",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单3-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }]
}, {
    "menuName": "服务",
    "subMenus": [{
        "subMenuName": "服务-子菜单1",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单1-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "服务-子菜单2",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单2-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "服务-子菜单3",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单3-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }]
}, {
    "menuName": "关于",
    "subMenus": [{
        "subMenuName": "关于-子菜单1",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单1-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "关于-子菜单2",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单2-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "关于-子菜单3",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单3-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }]
}, {
    "menuName": "帮助",
    "subMenus": [{
        "subMenuName": "帮助-子菜单1",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单1-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单1-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "帮助-子菜单2",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单2-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单2-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }, {
        "subMenuName": "帮助-子菜单3",
        "icon": "icon-sys",
        "items": [{
            "itemName": "子菜单3-子项1",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项2",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项3",
            "icon": "icon-nav",
            "url": ""
        }, {
            "itemName": "子菜单3-子项4",
            "icon": "icon-nav",
            "url": ""
        }]
    }]
}]